name: star event workflow

on:
  watch:

jobs:
  log_star_event:
    runs-on: ubuntu-latest

    steps:
      - name: Log star event
        run: |
          echo "Repository starred by $GITHUB_ACTOR"
          cat $GITHUB_EVENT_PATH
